import json
from pathlib import Path

import pytest

from engine.team_strength import PlayerCtx
from engine.trades import evaluate

SLOTS = {"QB": 1, "RB": 1}
ELIGIBILITY = {"QB": {"QB"}, "RB": {"RB"}}
WEEKS = [1, 2, 3]

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "trade_case.json"


def _players():
    def p(pid, pos, ppw):
        return PlayerCtx(id=pid, position=pos, ros_total=ppw * len(WEEKS), weekly={w: ppw for w in WEEKS})

    return {
        "qbA1": p("qbA1", "QB", 18.0),
        "rbA1": p("rbA1", "RB", 20.0),
        "rbA2": p("rbA2", "RB", 5.0),
        "qbB1": p("qbB1", "QB", 10.0),
        "rbB1": p("rbB1", "RB", 8.0),
        "rbB2": p("rbB2", "RB", 22.0),
    }


ROSTER_A = ["qbA1", "rbA1", "rbA2"]
ROSTER_B = ["qbB1", "rbB1", "rbB2"]


def test_trade_favors_a():
    players = _players()
    result = evaluate(
        gives_a=["rbA2"], gives_b=["rbB2"], roster_a=ROSTER_A, roster_b=ROSTER_B,
        players=players, weeks=WEEKS, slots=SLOTS, eligibility=ELIGIBILITY,
    )
    assert result.side_a.before == pytest.approx(114.0)  # (18+20)*3
    assert result.side_a.after == pytest.approx(120.0)  # (18+22)*3
    assert result.side_a.gain == pytest.approx(6.0)
    assert result.side_b.before == pytest.approx(96.0)  # (10+22)*3
    assert result.side_b.after == pytest.approx(54.0)  # (10+8)*3
    assert result.side_b.gain == pytest.approx(-42.0)
    assert result.favors == "a"


def test_trade_favors_b():
    players = _players()
    result = evaluate(
        gives_a=["rbA1"], gives_b=["rbB1"], roster_a=ROSTER_A, roster_b=ROSTER_B,
        players=players, weeks=WEEKS, slots=SLOTS, eligibility=ELIGIBILITY,
    )
    assert result.side_a.gain == pytest.approx(-36.0)
    assert result.side_b.gain == pytest.approx(0.0)
    assert result.favors == "b"


def test_trade_even_when_neither_lineup_changes():
    players = _players()
    result = evaluate(
        gives_a=["rbA2"], gives_b=["rbB1"], roster_a=ROSTER_A, roster_b=ROSTER_B,
        players=players, weeks=WEEKS, slots=SLOTS, eligibility=ELIGIBILITY,
    )
    assert result.side_a.gain == pytest.approx(0.0)
    assert result.side_b.gain == pytest.approx(0.0)
    assert result.favors == "even"


def test_weekly_breakdown_sums_to_gain_and_matches_before_after():
    players = _players()
    result = evaluate(
        gives_a=["rbA2"], gives_b=["rbB2"], roster_a=ROSTER_A, roster_b=ROSTER_B,
        players=players, weeks=WEEKS, slots=SLOTS, eligibility=ELIGIBILITY,
    )
    assert len(result.side_a.weekly) == 3
    assert sum(w["delta"] for w in result.side_a.weekly) == pytest.approx(result.side_a.gain)
    assert sum(w["before"] for w in result.side_a.weekly) == pytest.approx(result.side_a.before)
    assert sum(w["after"] for w in result.side_a.weekly) == pytest.approx(result.side_a.after)
    # constant weekly inputs -> every week's delta should be identical (2.0/wk)
    assert all(w["delta"] == pytest.approx(2.0) for w in result.side_a.weekly)


def test_raw_given_received_are_ros_totals():
    players = _players()
    result = evaluate(
        gives_a=["rbA2"], gives_b=["rbB2"], roster_a=ROSTER_A, roster_b=ROSTER_B,
        players=players, weeks=WEEKS, slots=SLOTS, eligibility=ELIGIBILITY,
    )
    assert result.side_a.raw_given == pytest.approx(15.0)  # rbA2 ros_total = 5*3
    assert result.side_a.raw_received == pytest.approx(66.0)  # rbB2 ros_total = 22*3


def test_fixture_matches_committed_json():
    """Regenerated by scripts in this file's __main__ block if the engine's
    trade math ever intentionally changes; docs/js/trade.js (Stage 6) is
    checked against this same fixture for parity."""
    with open(FIXTURE_PATH, encoding="utf-8") as f:
        fixture = json.load(f)

    players = _players()
    for case in fixture["cases"]:
        result = evaluate(
            gives_a=case["gives_a"], gives_b=case["gives_b"], roster_a=ROSTER_A, roster_b=ROSTER_B,
            players=players, weeks=WEEKS, slots=SLOTS, eligibility=ELIGIBILITY,
        )
        assert result.side_a.gain == pytest.approx(case["expected"]["gain_a"])
        assert result.side_b.gain == pytest.approx(case["expected"]["gain_b"])
        assert result.favors == case["expected"]["favors"]
